### Overview 
In this activity, learners work with text embeddings generated by a Large Language Model 
(LLM) to understand how machines represent meaning numerically. Instead of generating 
natural language responses, the model converts text into high-dimensional vectors, which 
can be mathematically compared to measure semantic similarity. 

This activity focuses on embedding generation, vector inspection, and cosine similarity computation, forming the 
foundation for semantic search and Retrieval-Augmented Generation systems. 

#### Learning Objectives 

- Generate text embeddings using an LLM embedding API. 
- Inspect embedding vectors and understand their dimensional properties. 
- Compute cosine similarity between embedding vectors. 
- Compare semantic similarity across multiple text pairs. 
- Understand why semantic similarity differs from keyword-based matching.

#### Tools Required 

- Web browser (Chrome recommended) 
- Google account 
- Google Colab 
 
To run locally

- Python
- VSCode

In [7]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

In [8]:
sentences = [
    # Sports domain 
    "I love playing cricket", 
    "I enjoy outdoor sports", 
    "Football is my favorite game", 
 
    # Finance domain 
    "The stock market is volatile today", 
    "Share prices fluctuate frequently", 
    "Investing requires patience", 
 
    # Technology domain 
    "Artificial intelligence is transforming industries", 
    "AI is changing how businesses operate", 
 
    # Completely unrelated 
    "I cooked pasta for dinner last night"
    "I love to code",
    "I want to fall in love",
    "Give me some food"
]

sentences

['I love playing cricket',
 'I enjoy outdoor sports',
 'Football is my favorite game',
 'The stock market is volatile today',
 'Share prices fluctuate frequently',
 'Investing requires patience',
 'Artificial intelligence is transforming industries',
 'AI is changing how businesses operate',
 'I cooked pasta for dinner last nightI love to code',
 'I want to fall in love',
 'Give me some food']

In [17]:
model = SentenceTransformer("all-MiniLM-L6-V2")
embeddings = model.encode(sentences)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 4575.06it/s]

In [18]:
embeddings

array([[ 4.9958229e-02,  3.3321358e-02, -2.3285395e-03, ...,
         1.1092095e-02,  8.0102960e-05, -6.7105681e-02],
       [ 2.9499829e-02,  1.4411370e-02,  6.5416336e-02, ...,
        -3.7658945e-02, -5.9858728e-02,  9.2734611e-03],
       [-3.8407970e-02, -2.2283206e-02, -5.5162329e-03, ...,
         8.8887461e-02,  4.8277970e-02, -1.1737626e-02],
       ...,
       [-5.4567322e-02, -3.5075273e-02, -1.2316642e-03, ...,
         1.0563122e-01, -6.7035504e-02, -1.0005950e-01],
       [-5.5572212e-02, -3.8670402e-02,  3.6618371e-02, ...,
         1.8383857e-02,  8.5113101e-02, -3.5774432e-02],
       [-3.9771970e-02,  3.3003822e-02,  1.3081932e-02, ...,
         1.3481849e-03, -4.6307802e-02, -9.8408356e-02]],
      shape=(11, 384), dtype=float32)

In [19]:
embeddings.shape

(11, 384)

In [21]:
df = pd.DataFrame(embeddings)
df

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
0,0.049958,0.033321,-0.002329,-0.051584,0.007579,0.017020,0.068801,0.038773,0.020014,0.155072,...,0.019295,0.052321,-0.098941,-0.027661,-0.007501,0.056552,0.086663,0.011092,0.000080,-0.067106
1,0.029500,0.014411,0.065416,0.014959,0.059126,-0.022189,0.105090,-0.007111,0.029928,0.075140,...,-0.005691,0.058608,-0.072654,-0.014891,-0.008932,0.013667,-0.010028,-0.037659,-0.059859,0.009273
2,-0.038408,-0.022283,-0.005516,-0.080521,0.036002,0.055260,0.053351,0.017533,0.117917,0.076751,...,0.092537,0.056813,-0.045154,-0.002984,0.018692,-0.008061,0.082945,0.088887,0.048278,-0.011738
3,0.024445,-0.056716,0.017313,0.069042,-0.008382,-0.007958,0.066339,-0.051165,0.053763,-0.008331,...,0.006561,0.007712,-0.058042,-0.000274,-0.069757,-0.088000,0.025691,-0.057957,-0.069058,0.065245
4,0.038124,-0.040106,0.044926,0.088392,-0.031368,-0.037588,-0.006287,-0.073798,0.113170,-0.011239,...,0.023778,-0.070113,-0.016920,-0.022773,-0.072017,-0.035288,-0.025008,-0.105827,-0.129638,0.021056
5,0.073088,-0.005522,-0.074722,0.032304,-0.022903,-0.023695,0.018369,-0.021885,0.010895,0.035073,...,-0.000484,0.032217,-0.045980,0.038209,-0.009198,-0.024945,0.005043,-0.102637,-0.059042,0.039043
6,0.030843,-0.021003,0.052753,-0.010596,0.044158,0.014099,-0.012389,-0.002453,-0.012590,-0.035113,...,0.083720,-0.023753,0.040317,-0.014297,-0.081419,0.079211,0.027523,-0.093771,0.075274,-0.025993
7,0.011302,-0.042873,0.040559,-0.009871,0.005123,0.038777,0.014080,-0.012688,0.045038,-0.036640,...,0.152255,-0.058541,0.034378,-0.061126,-0.027443,0.069663,-0.028032,-0.038099,0.056098,-0.030659
8,-0.054567,-0.035075,-0.001232,0.029131,-0.076673,-0.026662,0.044892,-0.022210,0.002349,-0.075430,...,0.051273,-0.028600,-0.013065,0.007530,0.065634,0.043042,0.021129,0.105631,-0.067036,-0.100060
9,-0.055572,-0.038670,0.036618,0.010712,0.012412,-0.006485,0.048534,0.037692,0.102784,-0.000113,...,-0.056090,-0.001226,-0.031107,0.067010,0.049066,-0.018571,0.044880,0.018384,0.085113,-0.035774
10,-0.039772,0.033004,0.013082,0.010639,-0.028451,0.011579,0.097971,-0.050282,-0.018018,-0.042596,...,0.013125,0.075059,0.040145,0.016531,0.056010,0.003750,-0.033975,0.001348,-0.046308,-0.098408

In [23]:
similarity_matrix = cosine_similarity(embeddings)
similarity_matrix

array([[ 1.0000002 ,  0.55957067,  0.49030012,  0.07040986,  0.01332199,
         0.10401235,  0.10506292,  0.03048856,  0.16772754,  0.24542166,
         0.18912277],
       [ 0.55957067,  0.9999999 ,  0.5524955 ,  0.13652208, -0.01701016,
         0.10656407,  0.10174075,  0.00558878,  0.07145879,  0.18874505,
         0.18400165],
       [ 0.49030012,  0.5524955 ,  0.99999976,  0.07382495, -0.0426203 ,
         0.05246718,  0.11978766,  0.00238412,  0.15625519,  0.14151607,
         0.17348014],
       [ 0.07040986,  0.13652208,  0.07382495,  1.0000001 ,  0.45949638,
         0.44279873,  0.2503247 ,  0.22523406,  0.06484033,  0.08208588,
         0.1096513 ],
       [ 0.01332199, -0.01701016, -0.0426203 ,  0.45949638,  0.99999976,
         0.31709078,  0.07983077,  0.15558963, -0.07888112, -0.02010753,
        -0.01738777],
       [ 0.10401235,  0.10656407,  0.05246718,  0.44279873,  0.31709078,
         1.0000002 ,  0.19285151,  0.24878943,  0.06800798,  0.09505191,
         0.05225888],
       [ 0.10506292,  0.10174075,  0.11978766,  0.2503247 ,  0.07983077,
         0.19285151,  1.        ,  0.74877006,  0.12874627,  0.10849382,
         0.02760123],
       [ 0.03048856,  0.00558878,  0.00238412,  0.22523406,  0.15558963,
         0.24878943,  0.74877006,  1.0000002 ,  0.16367488,  0.06427939,
         0.03604876],
       [ 0.16772754,  0.07145879,  0.15625519,  0.06484033, -0.07888112,
         0.06800798,  0.12874627,  0.16367488,  1.        ,  0.24855062,
         0.39861682],
       [ 0.24542166,  0.18874505,  0.14151607,  0.08208588, -0.02010753,
         0.09505191,  0.10849382,  0.06427939,  0.24855062,  0.9999999 ,
         0.2072857 ],
       [ 0.18912277,  0.18400165,  0.17348014,  0.1096513 , -0.01738777,
         0.05225888,  0.02760123,  0.03604876,  0.39861682,  0.2072857 ,
         1.0000002 ]], dtype=float32)

In [29]:
df_similarity = pd.DataFrame(
    similarity_matrix,
    columns=sentences,
    index=sentences
)

df_similarity

,I love playing cricket,I enjoy outdoor sports,Football is my favorite game,The stock market is volatile today,Share prices fluctuate frequently,Investing requires patience,Artificial intelligence is transforming industries,AI is changing how businesses operate,I cooked pasta for dinner last nightI love to code,I want to fall in love,Give me some food
I love playing cricket,1.000000,0.559571,0.490300,0.070410,0.013322,0.104012,0.105063,0.030489,0.167728,0.245422,0.189123
I enjoy outdoor sports,0.559571,1.000000,0.552495,0.136522,-0.017010,0.106564,0.101741,0.005589,0.071459,0.188745,0.184002
Football is my favorite game,0.490300,0.552495,1.000000,0.073825,-0.042620,0.052467,0.119788,0.002384,0.156255,0.141516,0.173480
The stock market is volatile today,0.070410,0.136522,0.073825,1.000000,0.459496,0.442799,0.250325,0.225234,0.064840,0.082086,0.109651
Share prices fluctuate frequently,0.013322,-0.017010,-0.042620,0.459496,1.000000,0.317091,0.079831,0.155590,-0.078881,-0.020108,-0.017388
Investing requires patience,0.104012,0.106564,0.052467,0.442799,0.317091,1.000000,0.192852,0.248789,0.068008,0.095052,0.052259
Artificial intelligence is transforming industries,0.105063,0.101741,0.119788,0.250325,0.079831,0.192852,1.000000,0.748770,0.128746,0.108494,0.027601
AI is changing how businesses operate,0.030489,0.005589,0.002384,0.225234,0.155590,0.248789,0.748770,1.000000,0.163675,0.064279,0.036049
I cooked pasta for dinner last nightI love to code,0.167728,0.071459,0.156255,0.064840,-0.078881,0.068008,0.128746,0.163675,1.000000,0.248551,0.398617
I want to fall in love,0.245422,0.188745,0.141516,0.082086,-0.020108,0.095052,0.108494,0.064279,0.248551,1.000000,0.207286
Give me some food,0.189123,0.184002,0.173480,0.109651,-0.017388,0.052259,0.027601,0.036049,0.398617,0.207286,1.000000

In [33]:
df_similarity.round(2)

,I love playing cricket,I enjoy outdoor sports,Football is my favorite game,The stock market is volatile today,Share prices fluctuate frequently,Investing requires patience,Artificial intelligence is transforming industries,AI is changing how businesses operate,I cooked pasta for dinner last nightI love to code,I want to fall in love,Give me some food
I love playing cricket,1.00,0.56,0.49,0.07,0.01,0.10,0.11,0.03,0.17,0.25,0.19
I enjoy outdoor sports,0.56,1.00,0.55,0.14,-0.02,0.11,0.10,0.01,0.07,0.19,0.18
Football is my favorite game,0.49,0.55,1.00,0.07,-0.04,0.05,0.12,0.00,0.16,0.14,0.17
The stock market is volatile today,0.07,0.14,0.07,1.00,0.46,0.44,0.25,0.23,0.06,0.08,0.11
Share prices fluctuate frequently,0.01,-0.02,-0.04,0.46,1.00,0.32,0.08,0.16,-0.08,-0.02,-0.02
Investing requires patience,0.10,0.11,0.05,0.44,0.32,1.00,0.19,0.25,0.07,0.10,0.05
Artificial intelligence is transforming industries,0.11,0.10,0.12,0.25,0.08,0.19,1.00,0.75,0.13,0.11,0.03
AI is changing how businesses operate,0.03,0.01,0.00,0.23,0.16,0.25,0.75,1.00,0.16,0.06,0.04
I cooked pasta for dinner last nightI love to code,0.17,0.07,0.16,0.06,-0.08,0.07,0.13,0.16,1.00,0.25,0.40
I want to fall in love,0.25,0.19,0.14,0.08,-0.02,0.10,0.11,0.06,0.25,1.00,0.21
Give me some food,0.19,0.18,0.17,0.11,-0.02,0.05,0.03,0.04,0.40,0.21,1.00

In [44]:
query_sentence = "Tell me what you know about love"
query_embeddings = model.encode([query_sentence])

query_similarities = cosine_similarity(query_embeddings, embeddings)
query_similarities

array([[ 2.3410504e-01,  1.5733781e-01,  2.2833049e-01,  9.7089492e-02,
        -1.9832514e-04,  2.5430191e-02,  1.2418715e-01,  3.5921104e-02,
         1.6310421e-01,  4.2913824e-01,  1.8515871e-01]], dtype=float32)

In [45]:
pd.DataFrame({ 
    "Sentence": sentences, 
    "Similarity Score": query_similarities [0]
}).sort_values(by="Similarity Score", ascending=False)

                                             Sentence  Similarity Score
9                              I want to fall in love          0.429138
0                              I love playing cricket          0.234105
2                        Football is my favorite game          0.228330
10                                  Give me some food          0.185159
8   I cooked pasta for dinner last nightI love to ...          0.163104
1                              I enjoy outdoor sports          0.157338
6   Artificial intelligence is transforming indust...          0.124187
3                  The stock market is volatile today          0.097089
7               AI is changing how businesses operate          0.035921
5                         Investing requires patience          0.025430
4                   Share prices fluctuate frequently         -0.000198